[package]
name = "crates_io"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2021"
default-run = "server"

[workspace]
members = ["crates/*"]

[workspace.lints.rust]
future_incompatible = "warn"
nonstandard_style = "warn"
rust_2018_idioms = "warn"
rust_2018_compatibility = "warn"
rust_2021_compatibility = "warn"
unused = "warn"

[workspace.lints.clippy]
all = "warn"
dbg_macro = "warn"
todo = "warn"

[lints]
workspace = true

[profile.release]
opt-level = 2

[lib]
name = "crates_io"
doctest = true

[[test]]
name = "all"
path = "src/tests/all.rs"

[features]
default = ["slow-tests"]

# The `slow-tests` enables tests that take a long time to finish. It is enabled
# by default but the test suite can be run via `cargo test --no-default-features`
# to disable these tests.
slow-tests = []

[dependencies]
anyhow = "=1.0.80"
async-trait = "=0.1.77"
aws-credential-types = { version = "=1.1.7", features = ["hardcoded-credentials"] }
aws-ip-ranges = "=0.135.0"
aws-sdk-cloudfront = "=1.15.0"
aws-sdk-sqs = "=1.15.0"
axum = { version = "=0.7.4", features = ["macros", "matched-path"] }
axum-extra = { version = "=0.9.2", features = ["cookie-signed", "typed-header"] }
base64 = "=0.22.0"
bigdecimal = { version = "=0.4.3", features = ["serde"] }
cargo-manifest = "=0.13.0"
crates_io_cdn_logs = { path = "crates/crates_io_cdn_logs" }
crates_io_env_vars = { path = "crates/crates_io_env_vars" }
crates_io_github = { path = "crates/crates_io_github" }
crates_io_index = { path = "crates/crates_io_index" }
crates_io_markdown = { path = "crates/crates_io_markdown" }
crates_io_tarball = { path = "crates/crates_io_tarball" }
crates_io_worker = { path = "crates/crates_io_worker" }
chrono = { version = "=0.4.34", default-features = false, features = ["serde"] }
clap = { version = "=4.5.2", features = ["derive", "env", "unicode", "wrap_help"] }
cookie = { version = "=0.18.0", features = ["secure"] }
dashmap = { version = "=5.5.3", features = ["raw-api"] }
deadpool = "=0.10.0"
deadpool-diesel = { version = "=0.5.0", features = ["postgres", "tracing"] }
derive_builder = "=0.20.0"
derive_deref = "=1.1.1"
dialoguer = "=0.11.0"
diesel = { version = "=2.1.6", features = ["postgres", "serde_json", "chrono", "r2d2", "numeric"] }
diesel_full_text_search = "=2.1.1"
diesel_migrations = { version = "=2.1.0", features = ["postgres"] }
dotenvy = "=0.15.7"
flate2 = "=1.0.28"
futures-util = "=0.3.30"
github-meta = "=0.11.0"
hex = "=0.4.3"
http = "=1.1.0"
http-body-util = "=0.1.0"
hyper = { version = "=1.2.0", features = ["client", "http1"] }
indexmap = { version = "=2.2.5", features = ["serde"] }
indicatif = "=0.17.8"
ipnetwork = "=0.20.0"
tikv-jemallocator = { version = "=0.5.4", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "=0.11.4", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
minijinja = "=1.0.12"
mockall = "=0.12.1"
moka = { version = "=0.12.5", features = ["future"]  }
oauth2 = { version = "=4.4.2", default-features = false, features = ["reqwest"] }
object_store = { version = "=0.9.1", features = ["aws"] }
once_cell = "=1.19.0"
p256 = "=0.13.2"
parking_lot = "=0.12.1"
paste = "=1.0.14"
prometheus = { version = "=0.13.3", default-features = false }
rand = "=0.8.5"
reqwest = { version = "=0.11.25", features = ["gzip", "json"] }
scheduled-thread-pool = "=0.2.7"
secrecy = "=0.8.0"
semver = { version = "=1.0.22", features = ["serde"] }
sentry = { version = "=0.32.2", features = ["tracing", "tower", "tower-axum-matched-path", "tower-http"] }
serde = { version = "=1.0.197", features = ["derive"] }
serde_json = "=1.0.114"
sha2 = "=0.10.8"
spdx = "=0.10.4"
tar = "=0.4.40"
tempfile = "=3.10.1"
thiserror = "=1.0.57"
tokio = { version = "=1.36.0", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread", "macros"]}
toml = "=0.8.10"
tower = "=0.4.13"
tower-http = { version = "=0.5.2", features = ["add-extension", "fs", "catch-panic", "timeout", "compression-full"] }
tracing = "=0.1.40"
tracing-subscriber = { version = "=0.3.18", features = ["env-filter"] }
typomania = { version = "=0.1.2", default-features = false }
url = "=2.5.0"
unicode-xid = "=0.2.4"

[dev-dependencies]
bytes = "=1.5.0"
crates_io_index = { path = "crates/crates_io_index", features = ["testing"] }
crates_io_tarball = { path = "crates/crates_io_tarball", features = ["builder"] }
crates_io_test_db = { path = "crates/crates_io_test_db" }
claims = "=0.7.1"
googletest = "=0.11.0"
insta = { version = "=1.36.1", features = ["json", "redactions"] }
regex = "=1.10.3"
tokio = "=1.36.0"
