[package]
name = "crates_io_tarball"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lints]
workspace = true

[features]
builder = []

[dependencies]
cargo-manifest = "=0.13.0"
flate2 = "=1.0.28"
serde = { version = "=1.0.197", features = ["derive"] }
serde_json = "=1.0.114"
tar = "=0.4.40"
thiserror = "=1.0.57"
tracing = "=0.1.40"

[dev-dependencies]
anyhow = "=1.0.80"
claims = "=0.7.1"
clap = { version = "=4.5.4", features = ["derive", "unicode", "wrap_help"] }
indicatif = { version = "=0.17.8", features = ["rayon"] }
rayon = "=1.9.0"
tracing-subscriber = { version = "=0.3.18", features = ["env-filter"] }
walkdir = "=2.5.0"
